use_frameworks!

platform :ios, '8.0'
source 'https://github.com/ny8080/cocoapods-spec.git'
source 'https://github.com/CocoaPods/Specs.git'

target 'ADBaseUIKit_Example' do
  pod 'ADBaseUIKit', :path => '../'
#   pod 'ADBaseUIKit',:podspec => '../ADBaseUIKit.podspec'
#  pod 'YYText'
  target 'ADBaseUIKit_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
